services:
  - type: web
    name: steeltilbud-frontend
    runtime: static
    rootDir: steeltilbud-frontend
    buildCommand: bun install && bun run build
    staticPublishPath: dist
    envVars:
      - key: VITE_API_URL
        value: https://steeltilbud-backend.onrender.com
      - key: BUN_VERSION
        value: 1.2.20
    routes:
      - type: rewrite
        source: /*
        destination: /index.html
